
REVOKE EXECUTE ON FUNCTION public.create_invoice_approval_chain() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.create_purchase_request_with_items(text, text, text, text, uuid, jsonb, text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.fn_apply_approved_material_excess(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_invoice_approval_cascade() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_recompute_auto_risks(text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_rollback_material_excess(uuid) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_seed_default_category_weights() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_sync_project_progress() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.fn_ticket_history() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_daily_report_detail(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_daily_reports_list(text, date, date, integer, integer) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_dashboard_summary(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_delayed_tasks_scoped(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_finans_overview(text, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_finans_overview_all(date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_my_projects() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_my_role() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_proje_detay(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_project_by_date(text, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_project_dashboard(text, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_project_gantt(text, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_project_overview(text, date, date) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_project_progress_export(text, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_santiye_dashboard(text, date) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_satin_alma_overview(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.get_satin_alma_overview_all() FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.has_project_access(text) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.log_ticket_changes() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_managers(text, uuid, text, uuid, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_role(text, uuid, text, text, uuid, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.notify_user(uuid, uuid, text, text, uuid, text, text, text) FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.save_daily_report(text, date, uuid, text, integer, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.sync_cost_allocation_from_invoice() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_purchase_request_from_invoice() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.sync_task_progress_from_daily() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_daily_report() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_invoice_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_invoice_status() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_purchase_request_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_purchase_request_status() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_ticket_comment() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_ticket_insert() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_notify_ticket_status() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_recompute_risks_from_daily_report() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_recompute_risks_from_purchase_item() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_recompute_risks_from_purchase_request() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.trg_recompute_risks_from_task() FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.user_can_access_report(uuid) FROM PUBLIC, anon;
REVOKE EXECUTE ON FUNCTION public.user_has_project_access(text) FROM PUBLIC, anon;

GRANT EXECUTE ON FUNCTION public.create_purchase_request_with_items(text, text, text, text, uuid, jsonb, text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_daily_report_detail(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_daily_reports_list(text, date, date, integer, integer) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_dashboard_summary(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_delayed_tasks_scoped(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_finans_overview(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_finans_overview_all(date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_projects() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_proje_detay(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_project_by_date(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_project_dashboard(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_project_gantt(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_santiye_dashboard(text, date) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_satin_alma_overview(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_satin_alma_overview_all() TO authenticated;
GRANT EXECUTE ON FUNCTION public.has_project_access(text) TO authenticated;
GRANT EXECUTE ON FUNCTION public.save_daily_report(text, date, uuid, text, integer, text, text, text, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb, jsonb) TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_can_access_report(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.user_has_project_access(text) TO authenticated;

